/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Sep 13, 2010, 4:41:30 PM
 */

package endecryptor;

/**
 *
 * @author serj
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane3 = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        inFile = new javax.swing.JTextField();
        inFileBrowse = new javax.swing.JButton();
        jSplitPane5 = new javax.swing.JSplitPane();
        outFile = new javax.swing.JTextField();
        outFileBrowse = new javax.swing.JButton();
        jSplitPane2 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSplitPane6 = new javax.swing.JSplitPane();
        keyStoreFile = new javax.swing.JTextField();
        keyStoreBrowse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        keyStorePassword = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        aliasCombo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        operationCombo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("7h3 b1n4rY 73r0r1s57 7001!");
        setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        setMinimumSize(new java.awt.Dimension(400, 182));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jSplitPane3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jSplitPane3.setResizeWeight(0.5);

        jSplitPane4.setResizeWeight(0.9);

        inFile.setText("Select input file");
        jSplitPane4.setLeftComponent(inFile);

        inFileBrowse.setText("...");
        inFileBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inFileBrowseActionPerformed(evt);
            }
        });
        jSplitPane4.setRightComponent(inFileBrowse);

        jSplitPane3.setLeftComponent(jSplitPane4);

        jSplitPane5.setResizeWeight(0.8);

        outFile.setText("Select output file");
        jSplitPane5.setLeftComponent(outFile);

        outFileBrowse.setText("...");
        outFileBrowse.setActionCommand("selectOutput");
        jSplitPane5.setRightComponent(outFileBrowse);
        outFileBrowse.getAccessibleContext().setAccessibleName("outputButton");

        jSplitPane3.setRightComponent(jSplitPane5);

        jSplitPane1.setTopComponent(jSplitPane3);

        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jButton1.setText("Go!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jSplitPane2.setBottomComponent(jButton1);

        jPanel3.setLayout(new java.awt.GridLayout(4, 0));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Key Store");
        jPanel3.add(jLabel4);

        jSplitPane6.setResizeWeight(0.9);
        jSplitPane6.setLeftComponent(keyStoreFile);

        keyStoreBrowse.setText("...");
        jSplitPane6.setRightComponent(keyStoreBrowse);

        jPanel3.add(jSplitPane6);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Key store password");
        jPanel3.add(jLabel5);

        keyStorePassword.setText("jPasswordField1");
        jPanel3.add(keyStorePassword);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Key store alias");
        jPanel3.add(jLabel6);

        aliasCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(aliasCombo);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Action to perform");
        jPanel3.add(jLabel7);

        operationCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(operationCombo);

        jSplitPane2.setTopComponent(jPanel3);

        jSplitPane1.setRightComponent(jSplitPane2);

        getContentPane().add(jSplitPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inFileBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inFileBrowseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inFileBrowseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aliasCombo;
    private javax.swing.JTextField inFile;
    private javax.swing.JButton inFileBrowse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JSplitPane jSplitPane5;
    private javax.swing.JSplitPane jSplitPane6;
    private javax.swing.JButton keyStoreBrowse;
    private javax.swing.JTextField keyStoreFile;
    private javax.swing.JPasswordField keyStorePassword;
    private javax.swing.JComboBox operationCombo;
    private javax.swing.JTextField outFile;
    private javax.swing.JButton outFileBrowse;
    // End of variables declaration//GEN-END:variables

}
